### ISSUE TITLE
posting msgpack records

### ISSUE THREAD

**Issue by ericmillin** [lestrrat-go/fluent-client#27]
I have written a Go output plugin for fluentbit. The records passed to the plugin are in msgpack format. The plugin forwards the unprocessed records to a server which uses `fluent-client` to post them to `in_forward`.

To get it to work, I have to decode and unmarshal the records to maps in order to post them. The client then encodes and marshals them. Is there a way to skip the decode-unmarshal-marshal-encode step and do something like 
```
client.Post("my-tag", rawMsgPackMsg)
```

or better yet
```
client.Post("my-tag", rawArrayOfMsgPackMsgs)
```
?

**Comment by lestrrat** [comment]
Not as of yet. I think you would need something like `client.PostRaw()`.

**Comment by lestrrat** [comment]
Hmm, this might be harder than I initially thought. Would you please create a failing test that describes how you would want the raw message posting would work?
